openapi: 3.0.3
info:
  title: Habit Tracker API
  version: 1.0.0

servers:
  - url: http://localhost:3000/api/v1

paths:
  /auth/signup:
    $ref: "./paths/auth/signup.yaml"
  /auth/login:
    $ref: "./paths/auth/login.yaml"
  /auth/logout:
    $ref: "./paths/auth/logout.yaml"
  /habits:
    $ref: "./paths/habits.yaml"
  /habits/{id}:
    $ref: "./paths/habitById.yaml"
  /completions:
    $ref: "./paths/completions.yaml"
  /completions/habit/{habitId}:
    $ref: "./paths/completionsByHabit.yaml"
  /completions/{habitId}/{date}:
    $ref: "./paths/deleteCompletion.yaml"

components:
  schemas:
    User:
      $ref: "./schemas/User.yaml"
    Habit:
      $ref: "./schemas/Habit.yaml"
    Completion:
      $ref: "./schemas/Completion.yaml"
    Error:
      $ref: "./schemas/Error.yaml"

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
